server:
  port: 8383
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:H:/Scaler/Backend/taskmgr-spring/testdb1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update